name: Daily GitHub Activity Tracker

on:
  schedule:
    - cron: "30 14 * * *"
  workflow_dispatch: # optional manual trigger

jobs:
  track_activity:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this tracker repo
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          sudo timedatectl set-timezone Asia/Colombo
          echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Fetch user repos via GitHub API
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          mkdir -p logs
          echo "# Daily Activity Report ($TODAY)" > logs/$TODAY.md
          echo "" >> logs/$TODAY.md
          echo "Generated at $(date '+%Y-%m-%d %H:%M:%S %Z')" >> logs/$TODAY.md
          echo "" >> logs/$TODAY.md

          # Fetch all repos you have access to
          repos=$(curl -s -H "Authorization: token $GH_TOKEN" "https://api.github.com/user/repos?per_page=100" | jq -r '.[].full_name')

          for repo in $repos; do
            # Get commits made today by you in that repo
            commits=$(curl -s -H "Authorization: token $GH_TOKEN" \
              "https://api.github.com/repos/$repo/commits?since=${TODAY}T00:00:00Z&until=${TODAY}T23:59:59Z&author=$(curl -s -H 'Authorization: token $GH_TOKEN' https://api.github.com/user | jq -r '.login')" \
              | jq -r '.[] | "- " + .commit.message + " (" + .html_url + ")"')

            if [ -n "$commits" ]; then
              echo "## [$repo](https://github.com/$repo)" >> logs/$TODAY.md
              echo "$commits" >> logs/$TODAY.md
              echo "" >> logs/$TODAY.md
            fi
          done

          if ! grep -q "##" logs/$TODAY.md; then
            echo "_No commits found for today._" >> logs/$TODAY.md
          fi

      - name: Ensure README exists and update Latest Activity section
        run: |
          README="README.md"
          # If README.md does not exist, create a basic one
          if [ ! -f "$README" ]; then
            echo "# Daily Commit Tracker" > "$README"
            echo "" >> "$README"
            echo "This repository collects a daily summary of commits across my projects." >> "$README"
            echo "" >> "$README"
          fi

          # Build the Latest Activity snippet
          LATEST_SNIPPET="## Latest activity (${TODAY})\n\n- Repositories scanned: ${TOTAL_REPOS_CHECKED}\n- Repositories changed: ${REPOS_WITH_COMMITS}\n- Total commits (you): ${TOTAL_COMMITS}\n\n[View detailed log](${LOG_FILE})\n\n"

          # Remove any previous "Latest activity" section (simple heuristic: remove first occurrence)
          # Keep the rest of README intact by removing from "## Latest activity" to the next blank line after two newlines
          awk -v RS='' -v ORS='\n\n' '
            BEGIN { printed=0 }
            {
              if ($0 ~ /^## Latest activity/) {
                if (printed==0) { printed=1; next }
              }
              print $0
            }' "$README" > "${README}.tmp" || cp "$README" "${README}.tmp"

          # Prepend the new Latest snippet to the README.tmp and overwrite README
          printf "%s\n\n%s" "$LATEST_SNIPPET" "$(cat ${README}.tmp)" > "$README"
          rm -f "${README}.tmp"

          echo "README updated. Preview:"
          sed -n '1,20p' README.md || true

      - name: Commit and push daily report
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "yasandu0505"
          git config user.email "yasanduyaka2005@gmail.com"
          git add logs/
          git commit -m "Add daily activity log for $TODAY" || echo "No changes to commit"
          git push https://x-access-token:${PAT_TOKEN}@github.com/yasandu0505/daily-commit-tracker.git
